dbt_tutorial:
  outputs:

    dev:
      type: postgres
      threads: 4
      host: db
      port: 5432
      user: postgres
      pass: postgres
      dbname: Adventureworks
      schema: warehouse

  target: dev
